spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/bank_accounts_test?useSSL=false&serverTimezone=UTC
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/bank_accounts_test
    username: root
    password:
    pool:
      enabled: true